server:
  port: 8082
spring:
  application:
    name: auth-service
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: http://localhost:9000
eureka:
  client:
    service-url:
      default-zone: http://172.18.0.2:8761/eureka/